### ISSUE TITLE
Able to put in more than 10 numbers, unable to delete below 10

### ISSUE THREAD

**Issue by techniq** [PolymerElements/gold-phone-input#18]
Checking out the [examples](https://elements.polymer-project.org/elements/gold-phone-input?view=demo:demo/index.html), if I input more than 10 numbers, the phone number formatting breaks (all hyphens are removed).  Once more than 10 characters are entered, you can no longer backspace/delete below 10 without selecting all first and then pressing delete.  Tested on Chrome 43.

**Comment by notwaldorf** [comment]
Ah good catch. The formatting breaks by design (the number no longer looks like the one we expect), but backspace should obviously work :)

**Comment by notwaldorf** [comment]
@techniq I've just cut a new release which *should* fix this problem (but makes the caret jump a little crazy after you delete the formatting. Looking into that). Does that work for you?

**Comment by techniq** [comment]
I am now able to delete back below the 10 characters after exceed it, but also see the odd caret issue you mentioned after you delete below 10 and the formatting is re-added.

**Comment by LM450N** [comment]
What about do not allowing to enter more chars than the defined pattern ?

**Comment by chunkzer** [comment]
Not allowing any more chars beyond the defined pattern would be preferred solution but to keep the formatting despite the input length works as well. You could say that dropping formatting after max length is good UX but that's what auto-validate should be for, no?

**Comment by claymation296** [comment]
Fixed both issues by adding (maxlength="12") attribute to the <input> found in gold-phone-input.html and a '-' to the allowed-pattern attr making it (allowed-pattern="[0-9-]").

Please be gentle, Im very new to all of this coding stuff

**Comment by claymation296** [comment]
Guess i should have looked at the latest version since it appears these fixes have already been applied.
