### ISSUE TITLE
Expose a method to get the international phone number format

### ISSUE THREAD

**Issue by LM450N** [PolymerElements/gold-phone-input#21]
It's a proposal. What do you think about expose a method to get the international phone number format. I mean the value prefixed by the country code.

_Example:_

![image](https://cloud.githubusercontent.com/assets/2325091/8617261/68111bba-2702-11e5-8fcb-0ebda94abfd2.png)

```javascript
var value = goldPhoneInput.value;
console.log(value); // "2-32-32-32-32"

var internationalValue = goldPhoneInput.internationalValue();
console.log(internationalValue); // "+(32)2-32-32-32-32"
```

Please, tell me if it's a good idea or not and why. :mortar_board:

**Comment by notwaldorf** [comment]
Oh, that's totally a good idea. I think the value should actually include the area code by default (since in the future the area code should be a dropdown)

**Comment by LM450N** [comment]
Yes ! I had the same idea ! I would like to have a drop down but you know,
a separate element. It could return an object with country code, money unit
and so on. And it could be connected directly with other components who
need choose location. What do you think about it ?

Louchart Mason - Cloud Computing and Mobility - from my Nexus 5
@LM450N | +MasonLouchart | www.louchart-mason.fr

**Comment by LM450N** [comment]
This issue is still relevant or should I to close it ?

**Comment by notwaldorf** [comment]
I think this is still a good enhancement!
