### ISSUE TITLE
TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by govis** [PolymerElements/gold-phone-input#23]
Hi, _computeValue appears to be throwing the error when gold-phone-input's value is undefined. I have it bound to a nested property:

<code>&lt;gold-phone-input value="{{model.phone}}">&lt;/gold-phone-input></code>

So even if I initialize model's phone property to an empty string, gold-phone-input still gets undefined prior to model itself being initialized.

Simple check for null might be needed in _computeValue. Thanks.

**Comment by FdezI** [comment]
Having the same issue.
