### ISSUE TITLE
Add a pass through for maxLength to the inner iron-input (Simple Q/A)

### ISSUE THREAD

**Issue by Gwynnie** [PolymerElements/gold-phone-input#24]
Would it be possible to add a maxLength pass through on ~line 95 ish.

Which would look like:
```
maxLength$="[[maxLength]]"
```
This would allow you to manually constrain the input to the length of the pattern.
(Or did I miss how you were meant to do this?)

**Comment by notwaldorf** [comment]
I'm working on refactoring the gold elements so that they automagically pass all their attributes to a `paper-input`. Stay tuned!
