### ISSUE TITLE
Uncaught TypeError: this._handleAutoValidate is not a function

### ISSUE THREAD

**Issue by CragVFX** [PolymerElements/gold-phone-input#29]
After updating gold-phone-input, I ran into an issue where I'm getting the following error, I do not see any reference to _handleAutoValidate within gold-phone-input.

<gold-phone-input id="someNum" country-code="1" label="Some Number" value="{{someNumber}}" auto-validate phone-number-pattern="XXX-XXX-XXXX"></gold-phone-input>

I get the same error if I just use:

<gold-phone-input></gold-phone-input>

I went from 1.0.0 => 1.0.6, now getting same error going back to 1.0.0

Any ideas?

**Comment by notwaldorf** [comment]
`_handleAutoValidate` lives in `PaperInputBehavior` (https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L335). Can you do a `bower cache clean && bower install` to make sure you're picking the latest `paper-input` release, please?

**Comment by CragVFX** [comment]
Thanks @notwaldorf! That was the issue. I appreciate it!
