### ISSUE TITLE
Null value error in _onValueChanged

### ISSUE THREAD

**Issue by govis** [PolymerElements/gold-phone-input#37]
<code>_onValueChanged</code> may throw <code>'TypeError: Cannot read property 'replace' of undefined'</code> exception if binding to <code>value</code> returns <code>undefined</code>.

Also the function makes use of both <code>this.value</code> property and <code>value</code> argument. It might be a good idea to stick with one for consistency.

**Comment by Ermish** [comment]
+1

**Comment by Ermish** [comment]
This issue was fixed in Merge #50 and can be closed.

**Comment by govis** [comment]
thanks
