### ISSUE TITLE
caret incorrectly jumps backward as input is added

### ISSUE THREAD

**Issue by jab** [PolymerElements/gold-phone-input#38]
I recently tested gold-phone-input 1.0.6 using Firefox on an Android phone, and observed the caret incorrectly jumping backward after inputting only 4 digits.

Here is a video demonstrating the bug:
https://youtu.be/xNAQoInBK28

Notice that the caret behaves as expected after entering the first 3 digits, but after entering the 4th, it jumps backward (to before the 2), so that further input is added behind the 2.

I saw mention of caret issues in #18 and #32, but noticed nothing yet mentioning an issue after only 4 characters / using a mobile / narrower width, so I'm hoping contributing this extra information might help.

**Comment by notwaldorf** [comment]
Hmm, this only seems to happen on mobile, eh? I'll take a look. Thanks!

**Comment by notwaldorf** [comment]
`paper-input` is also broken on mobile FF, so I think they share the same root cause. losing as dulicate of https://github.com/PolymerElements/paper-input/issues/273

**Comment by jab** [comment]
Thanks @notwaldorf, will follow over there. Sorry I didn't realize this turned out to be so much more general and high-priority.
