### ISSUE TITLE
Hide country code

### ISSUE THREAD

**Issue by kevashcraft** [PolymerElements/gold-phone-input#40]
This is a feature request to add the ability to hide the country code.

Hiding the country code is useful for applications limited to local users to tidy up the environment.

Also, the gold-phone-input could be used to capture social security and drivers license numbers if the country code could be hidden.

**Comment by jab** [comment]
(tangentially relevant: #42)

> Also, the gold-phone-input could be used to capture social security and drivers license numbers if the country code could be hidden.

Interesting. Note that some states' drivers license numbers have letters in them though. Sounds maybe worth spinning off a more general base element with a lot of gold-phone-input's current functionality, which allowed greater customization through options?
