### ISSUE TITLE
label alignment

### ISSUE THREAD

**Issue by jab** [PolymerElements/gold-phone-input#42]
gold-phone-input's label is currently aligned above the local part of the number, leaving a space above the country code, so if you have a series of paper-inputs one on each line, the phone input's label can look not-aligned with the others:

http://jsbin.com/sidifu/1/edit?html,output

What do you think?

**Comment by notwaldorf** [comment]
I think this could be used by using the `<prefix>` feature that has been added to `paper-input`

**Comment by miztroh** [comment]
Any update here?

**Comment by yordis** [comment]
@notwaldorf What do you mean? How can I do this today?
