### ISSUE TITLE
Move <script> inside <dom-module>

### ISSUE THREAD

**Issue by cherukumilli** [PolymerElements/gold-phone-input#51]
gold-phone-input's code is not following the same standards as other elements. gold-phone-input's javascript code is outside the <dom-module> </dom-module>. All other elements have javascript code inside the <dom-module> </dom-module> tags

### Current gold-phone-input code:
```
...
<dom-module>
   ...
</dom-module>
<script>
   ...
</script>
```

### Expected:
```
...
<dom-module>
   ...
   <script>
      ...
   </script>
</dom-module>
```

A similar issue has been fixed for other elements like paper-fab. Please check https://github.com/PolymerElements/paper-fab/pull/53 for details.

**Comment by notwaldorf** [comment]
Hi! Thanks for pointing this out! Would you be interested in sending a PR for that? 😻

**Comment by cherukumilli** [comment]
@notwaldorf 
I think [https://github.com/PolymerElements/gold-phone-input/issues/52](#52) needs to be fixed before fixing #51. If you think the solution to #52 is acceptable then I will submit PR's for each of them separately.

**Comment by notwaldorf** [comment]
Sounds good!

**Comment by notwaldorf** [comment]
@cherukumilli are you still interested in sending a PR for this?

**Comment by cherukumilli** [comment]
@notwaldorf - Yes. I will submit the pull request tomorrow morning.
