### ISSUE TITLE
Web Component Tester throwing error "done() called multiple times" on Chrome and Safari

### ISSUE THREAD

**Issue by cherukumilli** [PolymerElements/gold-phone-input#52]
Web Component Tester is throwing `done() called multiple times` error for a cloned PolymerElements/gold-phone-input element.

Please see the link below for error details.
[https://travis-ci.org/cherukumilli/gold-phone-input/builds/105506254]

Steps to recreate the problem on your local environment:

- git clone git@github.com:PolymerElements/gold-phone-input.git
- bower install
- wct

You will see errors like: (please see the link above for all the errors)

```
chrome 48                ✖ test/basic.html » basic » empty required input shows error on blur
  done() called multiple times
    <unknown> at   Suite.<anonymous> at basic.html:81:0
    <unknown> at           <unknown> at basic.html:46:0
```

**Comment by cherukumilli** [comment]
I see one way to fix the problem is by changing the test case 

**FROM:**
`      test('empty required input shows error on blur', function(done) {
        var input = fixture('required');
        forceXIfStamp(input);

        var error = Polymer.dom(input.root).querySelector('paper-input-error');
        assert.ok(error, 'paper-input-error exists');

        assert.equal(getComputedStyle(error).visibility, 'hidden', 'error is visibility:hidden');

        input.addEventListener('blur', function(event) {
          assert(!input.focused, 'input is blurred');
          assert.notEqual(getComputedStyle(error).visibility, 'hidden', 'error is not visibility:hidden');
          done();
        });
        MockInteractions.focus(input.inputElement);
        MockInteractions.blur(input.inputElement);
      });
`

**TO:**
`      test('empty required input shows error on blur', function(done) {
        var input = fixture('required');
        forceXIfStamp(input);

        var alreadyDone = false;

        var error = Polymer.dom(input.root).querySelector('paper-input-error');
        assert.ok(error, 'paper-input-error exists');

        assert.equal(getComputedStyle(error).visibility, 'hidden', 'error is visibility:hidden');

        input.addEventListener('blur', function(event) {
          assert(!input.focused, 'input is blurred');
          assert.notEqual(getComputedStyle(error).visibility, 'hidden', 'error is not visibility:hidden');

          if (!alreadyDone) {
            alreadyDone = true;
            done();
          }
        });
        MockInteractions.focus(input.inputElement);
        MockInteractions.blur(input.inputElement);
      });
`

If you are ok with this kind of change then I will submit a PR.

**Comment by notwaldorf** [comment]
Thanks for spotting this! Either that, or something similar to the fix in https://github.com/PolymerElements/gold-cc-input/issues/38 will work. A PR would be much appreciated! :)

**Comment by cherukumilli** [comment]
@notwaldorf 
Submitted PR# `[53](https://github.com/PolymerElements/gold-phone-input/pull/53)` (https://github.com/PolymerElements/gold-phone-input/pull/53) to fix this issue. Please check and if needed merge.
