### ISSUE TITLE
Documentation states "change" should be fired when the input changes due to user interaction.

### ISSUE THREAD

**Issue by GeoffAtHome** [PolymerElements/gold-phone-input#77]
### Description
Documentation states "change" should be fired when the input changes due to user interaction.

### Expected outcome
'change' event should be fired.

### Actual outcome
No 'change' event seen.

### Steps to reproduce
Use element as below:
        <gold-phone-input label="" country-code="44" phone-number-pattern="XXXX-XXX-XXX" auto-validate on-change="_inputHasChanged"

_inputHasChanged is never called.

With a listeners
listeners: {
     'change': '_inputHasChanged',
},

_inputHasChanged is never called.

Similar issues seen with gold-email-input.

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
Not tested on other browsers.

**Comment by notwaldorf** [comment]
Are you tabbing away from the field? The `change` event, unlike the `input` event is not fired every time you type, but rather when the element loses focus.

Here's an example: http://jsbin.com/tupumew/edit?html,console,output. If you tab (or click) away from each field, you'll see logs in the console.

Closing, as I can't repro this

**Comment by GeoffAtHome** [comment]
Thanks. I can see the example working. What I can't get working is doing this declarative. Attached is an example of this not working. My expectation is that it would work in a similar manner to how I have wrapped paper-input in the other attached example.

[phone-picker.zip](https://github.com/PolymerElements/gold-phone-input/files/895800/phone-picker.zip)
[input-picker.zip](https://github.com/PolymerElements/gold-phone-input/files/895802/input-picker.zip)
