### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by FallenRiteMonk** [PolymerElements/gold-phone-input#86]
Why isnt this published no longen on npm?

Last publish (https://www.npmjs.com/package/@polymer/gold-phone-input) was version 0.0.3 2 years ago!

I'm asking since I use ionic (which uses npm) and it would be great if don't have to add bower depencies just for this webcomponent!

**Comment by notwaldorf** [comment]
It is published on npm. As mentioned in the blog post, we're using the `@next` release for now. This is more obvious if you look at the `yarn` catalog: https://yarnpkg.com/en/package/@polymer/gold-phone-input (and 3.0.0-pre.1 was published on August 22, 2017)

**Comment by FallenRiteMonk** [comment]
Okey, thanks!
